# Generated by Django 5.2.5 on 2025-09-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_productcategory_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='BlogCategory',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blogs.blogcategory', verbose_name='دسته بندی'),
        ),
    ]
